import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://testautomationpractice.blogspot.com/');
  await page.getByRole('textbox', { name: 'Enter Name' }).click();
  await page.getByRole('textbox', { name: 'Enter Name' }).fill('Kalyan');
  await page.getByRole('textbox', { name: 'Enter Name' }).press('Tab');
  await page.getByRole('textbox', { name: 'Enter EMail' }).fill('kalyan89p@gmail.com');
  await page.getByRole('textbox', { name: 'Enter EMail' }).press('Tab');
  await page.getByRole('textbox', { name: 'Enter Phone' }).fill('9700989898');
  await page.getByRole('textbox', { name: 'Enter Phone' }).press('Tab');
  await page.getByRole('textbox', { name: 'Address:' }).fill('4602 Mallard Drive Melbourne FL 32932');
  await page.getByRole('textbox', { name: 'Address:' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Address:' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Address:' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Address:' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Address:' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Address:' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Address:' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Address:' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Address:' }).fill('4602 Mallard Drive Melbourne brevard FL 32932');
  await page.getByRole('radio', { name: 'Male', exact: true }).check();
  await page.getByRole('checkbox', { name: 'Sunday' }).check();
  await page.locator('div:nth-child(11) > div:nth-child(4)').click();
  await page.getByRole('checkbox', { name: 'Tuesday' }).check();
  await page.getByRole('checkbox', { name: 'Wednesday' }).check();
  await page.getByRole('checkbox', { name: 'Thursday' }).check();
  await page.getByRole('checkbox', { name: 'Friday' }).check();
  await page.getByRole('checkbox', { name: 'Saturday' }).check();
  await page.getByLabel('Country:').selectOption('uk');
  await page.getByLabel('Colors:').selectOption('yellow');
  await page.getByLabel('Sorted List:').selectOption('cheetah');
  await page.locator('#datepicker').click();
  await page.getByRole('link', { name: '16' }).click();
  await page.locator('#txtDate').click();
  await page.getByRole('link', { name: '30' }).click();
  await page.locator('#draggable').click();
  await page.locator('#draggable').click();
  await page.locator('#draggable').click();
  await page.locator('#field1').click();
  await page.locator('#field1').press('Shift+Home');
  await page.locator('#field1').fill('bye World');
  await page.locator('#field1').press('Tab');
  await page.locator('#field2').fill('Hi World');
  await page.getByRole('button', { name: 'Copy Text' }).click();
});